language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
  - npm install --prefix ./functions

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./client/node_modules    

script:
- npm --prefix ./client install ./client
- npm run lint --prefix ./client
- npm run build --prefix ./client
- firebase deploy --token $FIREBASE_TOKEN
#- npm run e2e --prefix ./client 


