language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
- ng lint
- ng build
after_success: 
- firebase use me-arash
- firebase deploy --token $FIREBASE_TOKEN
