language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
  - npm install --prefix ./functions
script:
- npm --prefix ./client install ./client
- npm run lint --prefix ./client
- npm run build --prefix ./client
after_success:
- firebase deploy --token $FIREBASE_TOKEN
